### ISSUE TITLE
cannot find openai_generator.py

### ISSUE THREAD

**Issue by 807660937** [OSU-NLP-Group/llm-planning-eval#2]
[from generators.openai_generator import OpenaiGenerator](https://github.com/OSU-NLP-Group/llm-planning-eval/blob/69829c721c9c89e6a698107907df4e388d094421/inference_py.py#L19)
but cannot find openai_generator.py

**Comment by kanseaveg** [comment]
![image](https://github.com/OSU-NLP-Group/llm-planning-eval/assets/80022154/7ed810aa-3c99-42eb-9a5e-0623a33727c9)

Encountered the same issue as you @807660937 , requesting the author @ronch99  to update, thank you.

**Comment by ziruch99** [comment]
Hi both,

Sorry for the confusion. In our paper, we eventually decided to use CodeLlama as the only generator to control the variables. Although we have tried to use OpenAI models as the generator in our preliminary experiments, those codes are now outdated (version 0.27.2) due to changes in the API. I've commented out the code imports.

If you would like to extend our framework to OpenAI generators, you may follow how we implemented the `HFGenerator` for the structure of generator class and `OpenaiEvaluator` for how to call the new API (version 1.8.0).

Sincerely,
Ron
